# Generated by Django 3.2.23 on 2023-12-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231201_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradress',
            name='adress_line_2',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='useradress',
            name='telephone',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
