# Generated by Django 3.2.23 on 2023-12-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231201_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradress',
            options={'verbose_name_plural': 'User addresses'},
        ),
    ]
