# Generated by Django 3.2.23 on 2023-12-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useradress_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAdress',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
