# Generated by Django 3.2.23 on 2023-12-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customshirt', '0002_customshirt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customshirt',
            name='image',
            field=models.ImageField(upload_to='custom_shirts'),
        ),
        migrations.AlterField(
            model_name='customshirt',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
