# Generated by Django 3.2.23 on 2023-12-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customshirt', '0004_customshirt_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customshirt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_shirts'),
        ),
    ]
