# Generated by Django 3.2.23 on 2023-12-21 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20231220_1502'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimonial', '0002_alter_testimonial_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
