# Generated by Django 3.2.23 on 2023-12-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20231220_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_cart',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='adress_line_1',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='order',
            name='adress_line_2',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
