# Generated by Django 3.2.23 on 2023-12-04 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_productcategory_options'),
        ('users', '0004_alter_useradress_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=7)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Refunded', 'Refunded')], default='Pending', max_length=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10)),
                ('shipping_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped')], default='Pending', max_length=10)),
                ('address_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='users.useradress')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='products.product')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-order_date',),
            },
        ),
        migrations.CreateModel(
            name='CancelledOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateField(auto_now_add=True)),
                ('cancel_reason', models.CharField(choices=[('Choose...', 'Choose...'), ('Defective', 'Defective'), ('Ordered wrong item', 'Ordered wrong item'), ('Unauthorized Purchase', 'Unauthorized purchase'), ('Just return', 'Just return')], default='Choose...', max_length=30)),
                ('other_reason', models.TextField()),
                ('cancel_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Granted', 'Granted'), ('Declined', 'Declined')], default='Pending', max_length=10)),
                ('resolved_on', models.DateField(auto_now_add=True)),
                ('order_number', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_id', to='orders.order')),
                ('resolved_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancel_user', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
