# Generated by Django 3.2.23 on 2023-12-08 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledorders',
            name='cancel_reason',
            field=models.CharField(choices=[('Choose...', 'Choose...'), ('Defective', 'Defective'), ('Ordered wrong item', 'Ordered wrong item'), ('Unauthorized Purchase', 'Unauthorized purchase'), ('Just return', 'I just want to return the item')], default='Choose...', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=7),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wishlist_product', to='products.product')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=5)),
                ('content', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_order', to='orders.order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
