# Generated by Django 3.2.23 on 2023-12-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20231211_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledorders',
            name='order_number',
            field=models.OneToOneField(editable=False, max_length=32, on_delete=django.db.models.deletion.PROTECT, related_name='order_id', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
