# Generated by Django 3.2.23 on 2023-12-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
